name: CI
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: .NET Setup
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Fetch submodules
      run: git submodule update --init --recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2

    - name: Navigate to workspace
      run: cd $GITHUB_WORKSPACE

    - name: Restore packages
      run: nuget restore UAssetGUI.sln

    - name: Build
      run: msbuild UAssetGUI.sln /p:Configuration=Release

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: |
          **/bin/Release/
          **/obj/Release/
